//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NationalCriminals.NationalCriminalsWcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProxy", Namespace="http://schemas.datacontract.org/2004/07/NationalCriminalsBusiness.Entities")]
    [System.SerializableAttribute()]
    public partial class UserProxy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriminalProxy", Namespace="http://schemas.datacontract.org/2004/07/NationalCriminalsBusiness.Entities")]
    [System.SerializableAttribute()]
    public partial class CriminalProxy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NationalCriminals.NationalCriminalsWcf.GenderType SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NationalCriminals.NationalCriminalsWcf.GenderType Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenderType", Namespace="http://schemas.datacontract.org/2004/07/NationalCriminalsBusiness.Enums")]
    public enum GenderType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriminalSearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/NationalCriminalsBusiness")]
    [System.SerializableAttribute()]
    public partial class CriminalSearchCriteria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IgnoreGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MaxAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MaxHeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxResultCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MaxWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinHeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IgnoreGender {
            get {
                return this.IgnoreGenderField;
            }
            set {
                if ((this.IgnoreGenderField.Equals(value) != true)) {
                    this.IgnoreGenderField = value;
                    this.RaisePropertyChanged("IgnoreGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMale {
            get {
                return this.IsMaleField;
            }
            set {
                if ((this.IsMaleField.Equals(value) != true)) {
                    this.IsMaleField = value;
                    this.RaisePropertyChanged("IsMale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxAge {
            get {
                return this.MaxAgeField;
            }
            set {
                if ((this.MaxAgeField.Equals(value) != true)) {
                    this.MaxAgeField = value;
                    this.RaisePropertyChanged("MaxAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxHeight {
            get {
                return this.MaxHeightField;
            }
            set {
                if ((this.MaxHeightField.Equals(value) != true)) {
                    this.MaxHeightField = value;
                    this.RaisePropertyChanged("MaxHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxResultCount {
            get {
                return this.MaxResultCountField;
            }
            set {
                if ((this.MaxResultCountField.Equals(value) != true)) {
                    this.MaxResultCountField = value;
                    this.RaisePropertyChanged("MaxResultCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxWeight {
            get {
                return this.MaxWeightField;
            }
            set {
                if ((this.MaxWeightField.Equals(value) != true)) {
                    this.MaxWeightField = value;
                    this.RaisePropertyChanged("MaxWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MinAge {
            get {
                return this.MinAgeField;
            }
            set {
                if ((this.MinAgeField.Equals(value) != true)) {
                    this.MinAgeField = value;
                    this.RaisePropertyChanged("MinAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MinHeight {
            get {
                return this.MinHeightField;
            }
            set {
                if ((this.MinHeightField.Equals(value) != true)) {
                    this.MinHeightField = value;
                    this.RaisePropertyChanged("MinHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MinWeight {
            get {
                return this.MinWeightField;
            }
            set {
                if ((this.MinWeightField.Equals(value) != true)) {
                    this.MinWeightField = value;
                    this.RaisePropertyChanged("MinWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NationalCriminalsWcf.INationalCriminalSvc")]
    public interface INationalCriminalSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalCriminalSvc/AddUser", ReplyAction="http://tempuri.org/INationalCriminalSvc/AddUserResponse")]
        bool AddUser(NationalCriminals.NationalCriminalsWcf.UserProxy user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalCriminalSvc/AddUser", ReplyAction="http://tempuri.org/INationalCriminalSvc/AddUserResponse")]
        System.Threading.Tasks.Task<bool> AddUserAsync(NationalCriminals.NationalCriminalsWcf.UserProxy user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalCriminalSvc/AddCriminal", ReplyAction="http://tempuri.org/INationalCriminalSvc/AddCriminalResponse")]
        bool AddCriminal(NationalCriminals.NationalCriminalsWcf.CriminalProxy criminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalCriminalSvc/AddCriminal", ReplyAction="http://tempuri.org/INationalCriminalSvc/AddCriminalResponse")]
        System.Threading.Tasks.Task<bool> AddCriminalAsync(NationalCriminals.NationalCriminalsWcf.CriminalProxy criminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalCriminalSvc/SearchCrininals", ReplyAction="http://tempuri.org/INationalCriminalSvc/SearchCrininalsResponse")]
        bool SearchCrininals(string email, NationalCriminals.NationalCriminalsWcf.CriminalSearchCriteria searchCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalCriminalSvc/SearchCrininals", ReplyAction="http://tempuri.org/INationalCriminalSvc/SearchCrininalsResponse")]
        System.Threading.Tasks.Task<bool> SearchCrininalsAsync(string email, NationalCriminals.NationalCriminalsWcf.CriminalSearchCriteria searchCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalCriminalSvc/GetUserInstanceFromDb", ReplyAction="http://tempuri.org/INationalCriminalSvc/GetUserInstanceFromDbResponse")]
        NationalCriminals.NationalCriminalsWcf.UserProxy GetUserInstanceFromDb(NationalCriminals.NationalCriminalsWcf.UserProxy user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalCriminalSvc/GetUserInstanceFromDb", ReplyAction="http://tempuri.org/INationalCriminalSvc/GetUserInstanceFromDbResponse")]
        System.Threading.Tasks.Task<NationalCriminals.NationalCriminalsWcf.UserProxy> GetUserInstanceFromDbAsync(NationalCriminals.NationalCriminalsWcf.UserProxy user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INationalCriminalSvcChannel : NationalCriminals.NationalCriminalsWcf.INationalCriminalSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NationalCriminalSvcClient : System.ServiceModel.ClientBase<NationalCriminals.NationalCriminalsWcf.INationalCriminalSvc>, NationalCriminals.NationalCriminalsWcf.INationalCriminalSvc {
        
        public NationalCriminalSvcClient() {
        }
        
        public NationalCriminalSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NationalCriminalSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalCriminalSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalCriminalSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddUser(NationalCriminals.NationalCriminalsWcf.UserProxy user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> AddUserAsync(NationalCriminals.NationalCriminalsWcf.UserProxy user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public bool AddCriminal(NationalCriminals.NationalCriminalsWcf.CriminalProxy criminal) {
            return base.Channel.AddCriminal(criminal);
        }
        
        public System.Threading.Tasks.Task<bool> AddCriminalAsync(NationalCriminals.NationalCriminalsWcf.CriminalProxy criminal) {
            return base.Channel.AddCriminalAsync(criminal);
        }
        
        public bool SearchCrininals(string email, NationalCriminals.NationalCriminalsWcf.CriminalSearchCriteria searchCriteria) {
            return base.Channel.SearchCrininals(email, searchCriteria);
        }
        
        public System.Threading.Tasks.Task<bool> SearchCrininalsAsync(string email, NationalCriminals.NationalCriminalsWcf.CriminalSearchCriteria searchCriteria) {
            return base.Channel.SearchCrininalsAsync(email, searchCriteria);
        }
        
        public NationalCriminals.NationalCriminalsWcf.UserProxy GetUserInstanceFromDb(NationalCriminals.NationalCriminalsWcf.UserProxy user) {
            return base.Channel.GetUserInstanceFromDb(user);
        }
        
        public System.Threading.Tasks.Task<NationalCriminals.NationalCriminalsWcf.UserProxy> GetUserInstanceFromDbAsync(NationalCriminals.NationalCriminalsWcf.UserProxy user) {
            return base.Channel.GetUserInstanceFromDbAsync(user);
        }
    }
}
